/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AjustesRouteImport } from './routes/ajustes'
import { Route as AmigosRouteImport } from './routes/amigos'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AyudaRouteImport } from './routes/ayuda'
import { Route as EspectarRouteImport } from './routes/espectar'
import { Route as JugarRouteImport } from './routes/jugar'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as RankingRouteImport } from './routes/ranking'
import { Route as TorneosRouteImport } from './routes/torneos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AjustesRoute = AjustesRouteImport.update({
  id: '/ajustes',
  path: '/ajustes',
  getParentRoute: () => rootRouteImport,
} as any)
const AmigosRoute = AmigosRouteImport.update({
  id: '/amigos',
  path: '/amigos',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AyudaRoute = AyudaRouteImport.update({
  id: '/ayuda',
  path: '/ayuda',
  getParentRoute: () => rootRouteImport,
} as any)
const EspectarRoute = EspectarRouteImport.update({
  id: '/espectar',
  path: '/espectar',
  getParentRoute: () => rootRouteImport,
} as any)
const JugarRoute = JugarRouteImport.update({
  id: '/jugar',
  path: '/jugar',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingRoute = RankingRouteImport.update({
  id: '/ranking',
  path: '/ranking',
  getParentRoute: () => rootRouteImport,
} as any)
const TorneosRoute = TorneosRouteImport.update({
  id: '/torneos',
  path: '/torneos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/espectar': typeof EspectarRoute
  '/jugar': typeof JugarRoute
  '/planes': typeof PlanesRoute
  '/ranking': typeof RankingRoute
  '/torneos': typeof TorneosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/espectar': typeof EspectarRoute
  '/jugar': typeof JugarRoute
  '/planes': typeof PlanesRoute
  '/ranking': typeof RankingRoute
  '/torneos': typeof TorneosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ajustes': typeof AjustesRoute
  '/amigos': typeof AmigosRoute
  '/auth': typeof AuthRoute
  '/ayuda': typeof AyudaRoute
  '/espectar': typeof EspectarRoute
  '/jugar': typeof JugarRoute
  '/planes': typeof PlanesRoute
  '/ranking': typeof RankingRoute
  '/torneos': typeof TorneosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ajustes'
    | '/amigos'
    | '/auth'
    | '/ayuda'
    | '/espectar'
    | '/jugar'
    | '/planes'
    | '/ranking'
    | '/torneos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ajustes'
    | '/amigos'
    | '/auth'
    | '/ayuda'
    | '/espectar'
    | '/jugar'
    | '/planes'
    | '/ranking'
    | '/torneos'
  id:
    | '__root__'
    | '/'
    | '/ajustes'
    | '/amigos'
    | '/auth'
    | '/ayuda'
    | '/espectar'
    | '/jugar'
    | '/planes'
    | '/ranking'
    | '/torneos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AjustesRoute: typeof AjustesRoute
  AmigosRoute: typeof AmigosRoute
  AuthRoute: typeof AuthRoute
  AyudaRoute: typeof AyudaRoute
  EspectarRoute: typeof EspectarRoute
  JugarRoute: typeof JugarRoute
  PlanesRoute: typeof PlanesRoute
  RankingRoute: typeof RankingRoute
  TorneosRoute: typeof TorneosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ajustes': {
      id: '/ajustes'
      path: '/ajustes'
      fullPath: '/ajustes'
      preLoaderRoute: typeof AjustesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/amigos': {
      id: '/amigos'
      path: '/amigos'
      fullPath: '/amigos'
      preLoaderRoute: typeof AmigosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ayuda': {
      id: '/ayuda'
      path: '/ayuda'
      fullPath: '/ayuda'
      preLoaderRoute: typeof AyudaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/espectar': {
      id: '/espectar'
      path: '/espectar'
      fullPath: '/espectar'
      preLoaderRoute: typeof EspectarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jugar': {
      id: '/jugar'
      path: '/jugar'
      fullPath: '/jugar'
      preLoaderRoute: typeof JugarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ranking': {
      id: '/ranking'
      path: '/ranking'
      fullPath: '/ranking'
      preLoaderRoute: typeof RankingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/torneos': {
      id: '/torneos'
      path: '/torneos'
      fullPath: '/torneos'
      preLoaderRoute: typeof TorneosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AjustesRoute: AjustesRoute,
  AmigosRoute: AmigosRoute,
  AuthRoute: AuthRoute,
  AyudaRoute: AyudaRoute,
  EspectarRoute: EspectarRoute,
  JugarRoute: JugarRoute,
  PlanesRoute: PlanesRoute,
  RankingRoute: RankingRoute,
  TorneosRoute: TorneosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
